### ISSUE TITLE
Assertion Error - block cache parsing

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/log-parser#24]
error: 
```
python3 log_parser.py -j -c short LOG  
Traceback (most recent call last):
  File "log_parser.py", line 352, in <module>
    main()
  File "log_parser.py", line 292, in main
    parsed_log = parse_log(log_file_path)
  File "log_parser.py", line 73, in parse_log
    return ParsedLog(log_file_path, log_lines,
  File "log-parser/log_file.py", line 184, in __init__
    self.parse_rest_of_log()
  File "log-parser/log_file.py", line 470, in parse_rest_of_log
    if self.try_parse_as_stats_entries():
  File "log-parser/log_file.py", line 412, in try_parse_as_stats_entries
    self.stats_mngr.try_adding_entries(self.log_entries,
  File "log-parser/stats_mngr.py", line 1139, in try_adding_entries
    self.parse_next_db_stats_entry_lines(
  File "log-parser/stats_mngr.py", line 1059, in parse_next_db_stats_entry_lines
    self.block_cache_stats_mngr.add_lines(time, cf_name,
  File "log-parser/stats_mngr.py", line 866, in add_lines
    self.parse_cf_entry_stats_line(time, cache_id, db_stats_lines[2])
  File "log-parser/stats_mngr.py", line 915, in parse_cf_entry_stats_line
    roles, roles_stats = BlockCacheStatsMngr.parse_entry_stats_line(
  File "log-parser/stats_mngr.py", line 939, in parse_entry_stats_line
    assert False, str(ParsingAssertion(
AssertionError: Error Parsing block cache stats line. roles:['DataBlock', 'FilterBlock'], roles_stats:['174.46 MB'][File:? (line#:?)]
 DataBlock(174.46 MB) FilterBlock(1
```
[LOG-readrandomwriterandom_70.zip](https://github.com/speedb-io/log-parser/files/12454883/LOG-readrandomwriterandom_70.zip)

LOG attached

**Comment by udi-speedb** [comment]
The CF stats line is only partially displayed (cropped):
`Block cache [column_family_name_000007]  DataBlock(174.46 MB) FilterBlock(1`

**Comment by udi-speedb** [comment]
@Yuval-Ariel - Please try to re-run using branch 24-assertion-error-block-cache-parsing and update if that helps. Thanks

**Comment by Yuval-Ariel** [comment]
yes it parses. main still fails on this so it needs to be merged
