### ISSUE TITLE
Assertion (TypeError) in calc_cfs_size_bytes_growth

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/log-parser#26]
udi@udi-speedb:~/log-parser$ python3 log_parser.py bug-logs/XMLOG.txt -j
Log file: file:///home/udi/log-parser/bug-logs/XMLOG.txt
Baseline Log: file:///home/udi/log-parser/baseline_logs/LOG-speedb-2.5.0
No Counters to report
No Counters Histograms to report
Compactions Stats CSV Is in file:///home/udi/log-parser/output_files/run_0009/compactions_stats.csv
No Compactions to report
Flushes CSV Is in file:///home/udi/log-parser/output_files/run_0009/flushes.csv
Traceback (most recent call last):
  File "log_parser.py", line 352, in <module>
    main()
  File "log_parser.py", line 314, in main
    json_content = generate_json_if_applicable(
  File "log_parser.py", line 217, in generate_json_if_applicable
    json_content = json_outputter.get_json(parsed_log)
  File "/home/udi/log-parser/json_outputter.py", line 197, in get_json
    j["DB-Size"] = get_db_size_json(parsed_log)
  File "/home/udi/log-parser/json_outputter.py", line 57, in get_db_size_json
    calc_utils.calc_cfs_size_bytes_growth(cfs_names,
  File "/home/udi/log-parser/calc_utils.py", line 122, in calc_cfs_size_bytes_growth
    if level in growth[cf_name]:
TypeError: argument of type 'NoneType' is not iterable

[XMLOG.txt](https://github.com/speedb-io/log-parser/files/12668841/XMLOG.txt)

**Comment by Yuval-Ariel** [comment]
that one works but this one fails :
[LOG_fails.txt](https://github.com/speedb-io/log-parser/files/12671049/LOG_fails.txt)

```
python3 log_parser.py -j -c short LOG
Traceback (most recent call last):
  File "log_parser.py", line 352, in <module>
    main()
  File "log_parser.py", line 292, in main
    parsed_log = parse_log(log_file_path)
  File "log_parser.py", line 73, in parse_log
    return ParsedLog(log_file_path, log_lines,
  File "log-parser/log_file.py", line 184, in __init__
    self.parse_rest_of_log()
  File "log-parser/log_file.py", line 470, in parse_rest_of_log
    if self.try_parse_as_stats_entries():
  File "log-parser/log_file.py", line 412, in try_parse_as_stats_entries
    self.stats_mngr.try_adding_entries(self.log_entries,
  File "log-parser/stats_mngr.py", line 1139, in try_adding_entries
    self.parse_next_db_stats_entry_lines(
  File "log-parser/stats_mngr.py", line 1059, in parse_next_db_stats_entry_lines
    self.block_cache_stats_mngr.add_lines(time, cf_name,
  File "log-parser/stats_mngr.py", line 864, in add_lines
    self.parse_global_entry_stats_line(time, cache_id, db_stats_lines[1])
  File "log-parser/stats_mngr.py", line 885, in parse_global_entry_stats_line
    assert line_parts and len(line_parts) == 1
AssertionError

```
