### ISSUE TITLE
parse_global_entry_stats_line error

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/log-parser#28]
this one fails :
[LOG_fails.txt](https://github.com/speedb-io/log-parser/files/12671049/LOG_fails.txt)

python3 log_parser.py -j -c short LOG
Traceback (most recent call last):
  File "log_parser.py", line 352, in <module>
    main()
  File "log_parser.py", line 292, in main
    parsed_log = parse_log(log_file_path)
  File "log_parser.py", line 73, in parse_log
    return ParsedLog(log_file_path, log_lines,
  File "log-parser/log_file.py", line 184, in __init__
    self.parse_rest_of_log()
  File "log-parser/log_file.py", line 470, in parse_rest_of_log
    if self.try_parse_as_stats_entries():
  File "log-parser/log_file.py", line 412, in try_parse_as_stats_entries
    self.stats_mngr.try_adding_entries(self.log_entries,
  File "log-parser/stats_mngr.py", line 1139, in try_adding_entries
    self.parse_next_db_stats_entry_lines(
  File "log-parser/stats_mngr.py", line 1059, in parse_next_db_stats_entry_lines
    self.block_cache_stats_mngr.add_lines(time, cf_name,
  File "log-parser/stats_mngr.py", line 864, in add_lines
    self.parse_global_entry_stats_line(time, cache_id, db_stats_lines[1])
  File "log-parser/stats_mngr.py", line 885, in parse_global_entry_stats_line
    assert line_parts and len(line_parts) == 1
AssertionError

**Comment by udi-speedb** [comment]
@Yuval-Ariel - Please check. Thanks

**Comment by Yuval-Ariel** [comment]
looks good
