### ISSUE TITLE
calc_delete_opers_stats error

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/log-parser#30]
Traceback (most recent call last):
  File "log_parser.py", line 352, in <module>
    main()
  File "log_parser.py", line 314, in main
    json_content = generate_json_if_applicable(
  File "log_parser.py", line 217, in generate_json_if_applicable
    json_content = json_outputter.get_json(parsed_log)
  File "/home/yuval/workspace/log-parser/json_outputter.py", line 187, in get_json
    j["General"] = get_general_json(parsed_log)
  File "/home/yuval/workspace/log-parser/json_outputter.py", line 29, in get_general_json
    general_json = display_utils.prepare_db_wide_info_for_display(parsed_log)
  File "/home/yuval/workspace/log-parser/display_utils.py", line 194, in prepare_db_wide_info_for_display
    db_wide_info = calc_utils.get_db_wide_info(parsed_log)
  File "/home/yuval/workspace/log-parser/calc_utils.py", line 334, in get_db_wide_info
    delete_opers_stats = calc_delete_opers_stats(cfs_names, events_mngr)
  File "/home/yuval/workspace/log-parser/calc_utils.py", line 214, in calc_delete_opers_stats
    assert cf_stats.unavailability_reason is not None
AssertionError

**Comment by udi-speedb** [comment]
@Yuval-Ariel - Please check

**Comment by Yuval-Ariel** [comment]
looks good
